image: mischief/docker-golang
env:
  - GOPATH=$PWD
  - EKKO_EX=/tmp/ekko
script:
  - go build -o $EKKO_EX ekko
  - go test -v ekko
notify:
  email:
    recipients:
      - partkyle@gmail.com
publish:
  ssh:
    user: git
    host: themoon.partkyle.com
    remote_path: /tmp
    commands:
      - ls
      - ls -ltr
