image: mischief/docker-golang
env:
  - GOPATH=$PWD
  - EKKO_EX=/tmp/ekko
script:
  - go build -o $EKKO_EX ekko
  - go test -v ekko
notify:
  email:
    recipients:
      - partkyle@gmail.com
publish:
  s3:
    acl: public-read
    access_key: {{aws_access_key}}
    secret_key: {{aws_secret_key}}
    bucket: {{aws_bucket}}
    source: $EKKO_EX
    target: /latest
